### ISSUE TITLE
Todo: make sure pseudo_density is always correctly spelled

### ISSUE THREAD

**Issue by benjaminleroy** [skgallagher/EpiCompare#15]
Clean up:

- [ ] Make sure `psuedo_density` is spelled correctly everywhere  (`distance_psuedo_density_function`'s return matrix doesn't have to correct spelling - just check everywhere)
- [ ] Remove functions not used anymore (see https://skgallagher.github.io/EpiCompare/reference/index.html)
    - [ ] look at index for poorly documented functions and redo. 
- [ ] change `local_distance_depth_function` to `distance_local_depth_function`.
- [ ] in website index: make `tidy_dist_mat` have it's own subsection (and not in geometry structure & depth)
- [ ] add `grid.arrange` and `arrangeGrob `to "special functions" on website index

**Comment by benjaminleroy** [comment]
`distance_psuedo_density_function`'s return matrix doesn't have to correct spelling - just check everywhere
